### ISSUE TITLE
Optimize for SSE 4.2 processors

### ISSUE THREAD

**Issue by rafael2k** [mozilla/LPCNet#138]
Do you think it makes sense to add a "vec_ssse3.h" and optimize for SSSE3/SSE 4.2-era processors (which I have a bunch of)?

**Comment by rafael2k** [comment]
Made a pull request for discussions:
https://github.com/mozilla/LPCNet/pull/139

**Comment by jmvalin** [comment]
I think it's a good idea to optimize for non-AVX CPUs, but perhaps not in the way you started. First, I suggest you have a look at the new exp_improved_simd2 branch, which significantly improves the AVX2 code (close to 2x speedup). I think the same optimizations can be directly converted to SSE* by just using two 128-bit instructions instead of each 256-bit instruction.

**Comment by rafael2k** [comment]
Thanks Jean-Marc, I'll take a look and try to "backport" to SSE 4.2 (Atom and Celeron) as you recommend. Btw, the new dot-product related functions also provide speed-up in the decoding?

**Comment by jmvalin** [comment]
The new code is only for decoding -- encoding is already pretty fast.

**Comment by rafael2k** [comment]
Right, encoding is really fast indeed. 
When I have something for SSE 4.2, should I just use the unit test in order to see if the results match the other implementations?
