### ISSUE TITLE
dump_data -train create huge files even for small input

### ISSUE THREAD

**Issue by zvik** [mozilla/LPCNet#16]
It seems that there is no test to see if the input ends on the second pass. So if the input data has less than 5M frames it will still generate huge features files.

I suggest changing https://github.com/mozilla/LPCNet/blob/master/src/dump_data.c#L264 to
```
if (!training || one_pass_completed) break;
```

**Comment by ahmed-fau** [comment]
Hi @zvik ,

Thanks for this tip. I need also to have training/feature data for only one pass. However, I could not understand how the change you have suggested could be applied because the line you have referred to is regarding allocation of an array.

Would it be possible to instead remove the `count*FRAME_SIZE_5MS>=10000000` at line [https://github.com/mozilla/LPCNet/blob/3a7ef33dcbade95ec08b85839b6268e35b8d3366/src/dump_data.c#L232](232) ?

The only thing which is changed from one pass to another is the random number generations, isn't it?

Best
