### ISSUE TITLE
Some explanation about the recent commits 

### ISSUE THREAD

**Issue by candlewill** [mozilla/LPCNet#21]
I have trained a model using the old code, and the model performs very well. In the recent 5 days, there are some new code update. Could @jmvalin or someone else take some explanation about these new update? Do I need to re-train the model using the new `dump_data` bin?

![image](https://user-images.githubusercontent.com/4916563/50584867-00610480-0ead-11e9-8d91-13ade3993234.png)

**Comment by jmvalin** [comment]
You don't *have* to retrain -- everything will keep working as it did. OTOH, if you do retrain, then you may get improved results. The changes basically improve how the noise gets added to the training data. These changes weren't really possible in Python without making the code *really* slow, which is why I rewrote it in C.

**Comment by candlewill** [comment]
I see. Thanks.
